[functions]


[functions.chatbot-query]
enabled = true
verify_jwt = true
import_map = "./functions/chatbot-query/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/chatbot-query/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/chatbot-query/*.html" ]

[functions.generar-rutina]
enabled = true
verify_jwt = false
import_map = "./functions/generar-rutina/deno.json"
entrypoint = "./functions/generar-rutina/index.ts"
